FROM node:bookworm-slim

# Install Nginx and OpenSSL
RUN apt-get update && apt-get install -y nginx openssl gettext

# Generate self-signed SSL certificate and key
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
-keyout /etc/ssl/private/server.key \
-out /etc/ssl/certs/server.crt \
-subj "/C=IT/ST=Lazio/L=Rome/O=main/CN=main.com"

# Change the default Nginx configuration
COPY nginx.conf /etc/nginx/nginx.conf.template
COPY start.sh /usr/local/bin/
RUN	chmod 755 /usr/local/bin/start.sh

WORKDIR /home/app/

COPY *.js *.json ./

RUN npm install

ENTRYPOINT ["/usr/local/bin/start.sh"]