FROM node:bookworm-slim

# Install Nginx and OpenSSL
RUN apt-get update && apt-get install -y nginx openssl

# Change the default Nginx configuration
RUN rm -v /etc/nginx/nginx.conf
COPY nginx.conf /etc/nginx/nginx.conf

# Generate self-signed SSL certificate and key
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
-keyout /etc/ssl/private/server.key \
-out /etc/ssl/certs/server.crt \
-subj "/C=IT/ST=Lazio/L=Rome/O=main/CN=main.com"

WORKDIR /home/app/

COPY *.js *.json ./

RUN npm install && npm rebuild

CMD npm run build & nginx -g 'daemon off;'