# Request authorization code
GET https://localhost/django/o/authorize/?response_type=code&client_id=vdvpt0LYovlFgq174j6dMEClpWLucl9fRgIhLKWd&redirect_uri=https://localhost/&scope=openid+profile+email&state=abc123&code_challenge=YOUR_CODE_CHALLENGE&code_challenge_method=S256 HTTP/1.1
Content-Type: application/json
