# Use the official Debian slim image as a base
FROM debian:bullseye-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Install system dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        python3 \
        python3-pip \
        postgresql-client \
    && rm -rf /var/lib/apt/lists/*

COPY ./requirements.txt ./entrypoint.sh /usr/src/
RUN pip install -r /usr/src/requirements.txt

WORKDIR /usr/src/app

COPY ./project .

ENTRYPOINT ["sh", "/usr/src/entrypoint.sh"]
