# Generated by Django 4.2 on 2024-08-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interest',
            field=models.CharField(blank=True, choices=[('sport', 'Sport'), ('reading', 'Reading'), ('relax', 'Relax'), ('prevention', 'Prevention'), ('other', 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married')], null=True),
        ),
    ]
