# Generated by Django 3.2.12 on 2024-07-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20240708_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksite',
            name='department',
            field=models.TextField(null=True),
        ),
    ]
