# Generated by Django 4.2 on 2024-08-19 08:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_interest_alter_user_marital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Enter a valid City. Only letters and spaces are allowed.', regex="^[A-Za-zÀ-ÖØ-öø-ÿ'\\s]+$")]),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Enter a valid Country. Only letters and spaces are allowed.', regex="^[A-Za-zÀ-ÖØ-öø-ÿ'\\s]+$")]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(message='Enter a valid name. Only letters and spaces are allowed.', regex="^[A-Za-zÀ-ÖØ-öø-ÿ'\\s]+$")]),
        ),
        migrations.AlterField(
            model_name='user',
            name='street',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Enter a valid street address. Only letters, numbers and spaces are allowed.', regex="^[0-9A-Za-zÀ-ÖØ-öø-ÿ'\\s]+$")]),
        ),
        migrations.AlterField(
            model_name='user',
            name='surname',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(message='Enter a valid surname. Only letters and spaces are allowed.', regex="^[A-Za-zÀ-ÖØ-öø-ÿ'\\s]+$")]),
        ),
    ]
