# Generated by Django 3.2.12 on 2024-08-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='childrens',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='elderly_parents',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='interest',
            field=models.CharField(blank=True, choices=[('sport', 'Sport'), ('reading', 'Reading'), ('relax', 'Relax'), ('prevention', 'Prevention'), ('other', 'Other')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='residence',
            field=models.TextField(blank=True, null=True),
        ),
    ]
