# Generated by Django 3.2.12 on 2024-07-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_worksite_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksite',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='worksite',
            name='department',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
