# Generated by Django 3.2.12 on 2024-08-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20240804_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksite',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worksite',
            name='department',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
