# Generated by Django 4.2 on 2024-08-19 11:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_city_alter_user_country_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(message='Enter a valid name. Only letters and spaces are allowed.', regex="^(?!\\s*$)[A-Za-zÀ-ÖØ-öø-ÿ'\\s]+$")]),
        ),
    ]
