# Generated by Django 3.2.12 on 2024-08-04 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20240804_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='worksite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.worksite'),
        ),
    ]
