# Generated by Django 4.2 on 2024-08-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_city_alter_user_country_alter_user_street_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interest',
            field=models.IntegerField(blank=True, choices=[(0, 'Sport'), (1, 'Reading'), (2, 'Relax'), (3, 'Prevention'), (4, 'Other')], null=True),
        ),
    ]
