# Generated by Django 3.2.12 on 2024-07-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20240709_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='home',
        ),
        migrations.AddField(
            model_name='user',
            name='domicile',
            field=models.TextField(blank=True),
        ),
    ]
