# Generated by Django 4.2 on 2024-08-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='marital_status',
            field=models.IntegerField(blank=True, choices=[(0, 'Single'), (1, 'Married')], null=True),
        ),
    ]
