# Generated by Django 3.2.12 on 2024-07-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20240713_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_married',
        ),
        migrations.AddField(
            model_name='user',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married')], max_length=10, null=True),
        ),
    ]
